export const fixtureData = [
  {
    status: 'readyToTry',
    imageUrl: '/images/adidas Originals LA Trainer OG.jfif',
    name: 'Adidas Originals LA Trainer OG',
    category: 'Men',
    size: 'UK 10',
    color: 'Grey/White',
    customerInitials: 'BB',
  },
  {
    status: 'onTheWay',
    imageUrl: '/images/adidas Originals Rod Laver.jfif',
    name: 'Adidas Originals Rod Laver',
    category: 'Men',
    size: 'UK 11',
    color: 'White',
    customerInitials: 'PP',
  },
  {
    status: 'inTheQueue',
    imageUrl: "/images/adidas Originals U_Path X.jfif",
    name: 'Adidas Originals U_Path X',
    category: 'Men',
    size: 'UK 11',
    color: 'Black',
    customerInitials: 'CX',
  },
  {
    status: 'outOfStock',
    imageUrl: "/images/adidas Originals ZX 750.jfif",
    name: 'Adidas Originals ZX 750',
    category: 'Men',
    size: 'UK 10',
    color: 'White',
    customerInitials: 'TS',
  },
  {
    status: 'readyToTry',
    imageUrl: '/images/Nike Air Force 1 \'07 LV8 Women\'s.jfif',
    name: 'Nike Air Force 1 \'07 LV8 Women\'s',
    category: 'Women',
    size: 'UK 7',
    color: 'Grey/White',
    customerInitials: 'JD',
  },
  {
    status: 'onTheWay',
    imageUrl: '/images/Nike Air Force 1 Utility Junior.jfif',
    name: 'Nike Air Force 1 Utility Junior',
    category: 'Junior',
    size: 'UK 4',
    color: 'Black',
    customerInitials: 'CY',
  },
  {
    status: 'inTheQueue',
    imageUrl: "/images/Nike Air Max 90 Slides.jfif",
    name: 'Nike Air Max 90 Slides',
    category: 'Men',
    size: 'UK 11',
    color: 'Blue/White',
    customerInitials: 'EY',
  },
  {
    status: 'outOfStock',
    imageUrl: "/images/Nike Air Max 95.jfif",
    name: 'Nike Air Max 95',
    category: 'Men',
    size: 'UK 11',
    color: 'Black',
    customerInitials: 'PS',
  },
  {
    status: 'readyToTry',
    imageUrl: '/images/Nike Air Max 270 Junior.jfif',
    name: 'Nike Air Max 270 Junior',
    category: 'Junior',
    size: 'UK 3',
    color: 'White',
    customerInitials: 'SW',
  },
  {
    status: 'onTheWay',
    imageUrl: '/images/Nike Air VaporMax 360.jfif',
    name: 'Nike Air VaporMax 360',
    category: 'Men',
    size: 'UK 9',
    color: 'Blue',
    customerInitials: 'IM',
  },
  {
    status: 'inTheQueue',
    imageUrl: "/images/Nike Air VaporMax 2019 Junior.jfif",
    name: 'Nike Air VaporMax 2019 Junior',
    category: 'Junior',
    size: 'UK 4',
    color: 'Grey',
    customerInitials: 'CD',
  },
  {
    status: 'outOfStock',
    imageUrl: "/images/Nike City Trainer 2 Women's.jfif",
    name: 'Nike City Trainer 2 Women\'s',
    category: 'Women',
    size: 'UK 6',
    color: 'Black/Grey',
    customerInitials: 'HT',
  },
]

export default fixtureData
